name: prometheus-lab
version: 2.2.1
summary: Prometheus
description: |
  Prometheus is a system monitoring tool.
architectures: [armhf]
confinement: devmode

parts:
  config-builder:
    plugin: python
    python-version: python3
    source: config-builder
  prometheus:
    plugin: dump
    source: https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-armv7.tar.gz
    prepare: rm NOTICE
  node-exporter:
    plugin: dump
    source: https://github.com/prometheus/node_exporter/releases/download/v0.15.2/node_exporter-0.15.2.linux-armv7.tar.gz
    prepare: rm NOTICE
apps:
  config-builder:
    command: python config-builder.py
  #  daemon: oneshot
  node-exporter:
    command: node_exporter
    daemon: simple
    plugs:
    - network
  prometheus:
    command: prometheus --config.file="$SNAP_COMMON/prometheus.yml"
    daemon: simple
    plugs:
    - network

